### ISSUE TITLE
When I am selecting the extendedDropdown in show time zone: The tool is getting hanged.

### ISSUE THREAD

**Issue by VikasBisht** [PredixDev/px-datetime-picker#10] opened 2016-12-12 17:28 UTC
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by nonmetalhail** [comment] 2016-12-12 17:48
If you would like help, please fill out the template and include sufficient detail that we can diagnose the issue.

**Comment by VikasBisht** [comment] 2016-12-12 17:52
I was setting up the tool locally.
When i set the show time zone with extended dropdown then the tool is getting hanged.
Its showing (index):6718 Uncaught RangeError: Maximum call stack size exceeded.(…).

I dont know whats causing this.
Could you please help me here.

**Comment by benoitjchevalier** [comment] 2016-12-12 18:02
Just ran the latest versions locally and I can't reproduce your problem. Can you please try to show us the problem in a codepen?

**Comment by VikasBisht** [comment] 2016-12-13 08:01
![image](https://cloud.githubusercontent.com/assets/24294854/21132065/6307cd16-c112-11e6-90f5-ec82a7f1e261.png)

If you will see in the above image there are a lot of console error coming for the exceeding stack value.

I believe there is some problem due to validate.html and polymer-date-entry.html.

Some sort of recursive calls which are leading it to stack full.

**Comment by Menkhaus-ge** [comment] 2016-12-14 19:56
Hi VikasBisht, 
We can reproduce this bug and are working on a fix. 
This issue seems to be tied to having the am/pm showing. While we work to find a solution if you use a 24 time format 'HH:mm' then you will not get this error. 
Thank you

**Comment by Menkhaus-ge** [comment] 2016-12-15 00:28
This issue has been fixed with the px-datetime-common v0.7.1 release. 
Thank you

**Closed by Menkhaus-ge** 2016-12-15 00:28 UTC

**Comment by VikasBisht** [comment] 2016-12-19 07:36
Thanks for resolving this .
I believe the same need to be fixed in Range picker as well.

**Comment by Menkhaus-ge** [comment] 2016-12-19 18:19
The rangepicker was having the same problem sense it also relies on px-datetime-common. The demo online has been updated and this problem should no longer occur. Make sure in your bower that you are bring in px-datetime-common v0.7.1.
