### ISSUE TITLE
The calendar picker panel choose wrong day when switch month

### ISSUE THREAD

**Issue by benjaminliugang** [PredixDev/px-datetime-picker#28] opened 2017-12-13 12:12 UTC
a) Open the calendar picker
b) Click the left month arrow icon to change the month, the month will switch to next month
We could find the day still mark as selected(Snapshot A), and when we click the right arrow icon back to the previous month, the day lost the selected color(Snapshot B).

**Snapshot A:**
![image](https://user-images.githubusercontent.com/1411188/33938020-c824d48e-e040-11e7-94ce-061231e6840e.png)

**Snapshot B:**
![image](https://user-images.githubusercontent.com/1411188/33938176-7020a528-e041-11e7-9e7d-012c2d5957cc.png)

**Comment by randyaskin** [comment] 2017-12-22 17:46
Duplicate of #14

**Closed by randyaskin** 2017-12-22 17:46 UTC
